name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        
        # MOONMODULES = HUB75 incluso
        wget https://github.com/MoonModules/WLED-MM/archive/refs/heads/mdev.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        cd /tmp/WLEDtemp/WLED-MM-mdev
        
        npm install
        
        # COMPILA env MoonModules CON HUB75 (MQTT giÃ  dentro)
        pio run -e esp32dev
        
        echo "/tmp/WLEDtemp/WLED-MM-mdev" > /tmp/WLEDtemp/wledfoldername
    
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        WLED_FOLDER=$(cat /tmp/WLEDtemp/wledfoldername)
        cp "$WLED_FOLDER/.pio/build/esp32dev/firmware.bin" $GITHUB_WORKSPACE/custom_build.bin
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt


    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
