name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Run PlatformIO (DEBUG)
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        
        wget https://github.com/wled/WLED/archive/refs/heads/main.zip -O /tmp/WLEDtemp/wled.zip
        unzip /tmp/WLEDtemp/wled.zip -d /tmp/WLEDtemp
        cd /tmp/WLEDtemp/WLED-main
        
        npm install
        
        # STAMPA TUTTI GLI ENVIRONMENT REALI
        echo "=== ENVIRONMENT DISPONIBILI ==="
        grep -E '^\[env:' platformio.ini | sed 's/\[env://g' | sed 's/\]/ (/g'
        
        # Prova compilazione DEFAULT (senza override)
        pio run -e esp32dev || echo "esp32dev NON ESISTE"
        pio run -e nodemcuv2 || echo "nodemcuv2 NON ESISTE"
        
        echo "/tmp/WLEDtemp/WLED-main" > /tmp/WLEDtemp/wledfoldername

    
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        WLED_FOLDER=$(cat /tmp/WLEDtemp/wledfoldername)
        cp "$WLED_FOLDER/.pio/build/esp32_mqtt/firmware.bin" $GITHUB_WORKSPACE/custom_build.bin
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt




    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
