name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        
        wget https://github.com/wled/WLED/archive/refs/heads/main.zip -O /tmp/WLEDtemp/wled.zip
        unzip /tmp/WLEDtemp/wled.zip -d /tmp/WLEDtemp
        cd /tmp/WLEDtemp/WLED-main
        
        npm install
        
        # Environment REALE + MQTT
        cat > platformio_override.ini << EOF
        [env:esp32_mqtt]
        extends = esp32dev_V4  ; <-- ESISTE nel platformio.ini [web:19]
        build_flags = 
          \${esp32dev_V4.build_flags}
          -D WLED_ENABLE_MQTT
          -D WLED_RELEASE_NAME="ESP32_MQTT"
        EOF
        
        pio run -e esp32_mqtt
        echo "/tmp/WLEDtemp/WLED-main" > /tmp/WLEDtemp/wledfoldername
    
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        WLED_FOLDER=$(cat /tmp/WLEDtemp/wledfoldername)
        cp "$WLED_FOLDER/.pio/build/esp32_mqtt/firmware.bin" $GITHUB_WORKSPACE/custom_build.bin
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt




    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
